version: "3.8"

services:
  app:
    container_name: adminota
    build: ./
    command: python run.py
    ports:
      - ${SERVER_PORT}:5000
    env_file:
      - .env
    extra_hosts:
      - host.docker.internal:${HOST_DOCKER_INTERNAL}
    restart: always
