name: Code checks

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install flake8
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 . --count --select=E501,E203,E402,E712,I001,I003,I004,I005,W503,F401,F821,F722 --max-line-length=79 --show-source --statistics
      - name: Test with pytest
        run: pytest
